spring:
  application:
    name: store-cqrs

# Configuración de PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

# Configuración de JPA/Hibernate
  jpa:
    hibernate:
      # validate = usar Flyway para esquema, no Hibernate
      ddl-auto: validate
    show-sql: false        # Ver SQL en desarrollo
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Configuración de Flyway para migraciones
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Configuración específica de Spring Modulith
  modulith:
    events:
      # ¿Qué hace? Guarda eventos procesados para auditoría
      # Alternativa: delete (elimina eventos procesados para ahorrar espacio)
      completion-mode: archive

      # ¿Para qué? Si la app se reinicia, re-procesa eventos pendientes
      # Garantiza que ningún evento se pierda
      republish-outstanding-events-on-restart: true

  # Logging para desarrollo - ver qué hace Spring Modulith
  logging:
    level:
      com.geovannycode.store: DEBUG
      org.springframework.modulith: DEBUG